[package]
name = "acid"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
glazer = { path = "../blaze/crates/glazer" }
lidsp = { path = "../blaze/crates/lidsp" }
